17/11/18 05:03:04.049 [pid:130] - error: uncaughtException: jsayers is not defined 
{ date: 'Sat Nov 18 2017 05:03:04 GMT+0000 (UTC)',
  process: 
   { pid: 130,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 86016000,
        heapTotal: 70062080,
        heapUsed: 38172536,
        external: 18007977 } },
  os: 
   { loadavg: [ 0.357421875, 0.25537109375, 0.4111328125 ],
     uptime: 275597 },
  trace: 
   [ { column: 22,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 442,
       method: null,
       native: false },
     { column: 3,
       file: 'fs.js',
       function: 'tryToString',
       line: 456,
       method: null,
       native: false },
     { column: 12,
       file: 'fs.js',
       function: 'FSReqWrap.readFileAfterClose [as oncomplete]',
       line: 443,
       method: 'readFileAfterClose [as oncomplete]',
       native: false } ],
  stack: 
   [ 'ReferenceError: jsayers is not defined',
     '    at /workspace/Assignment/server/controllers/fileManager.js:442:22',
     '    at tryToString (fs.js:456:3)',
     '    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)' ] }
17/11/18 05:27:49.451 [pid:201] - error: uncaughtException: Invalid data, chunk must be a string or buffer, not number 
{ date: 'Sat Nov 18 2017 05:27:49 GMT+0000 (UTC)',
  process: 
   { pid: 201,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 88993792,
        heapTotal: 70062080,
        heapUsed: 38141384,
        external: 18040745 } },
  os: 
   { loadavg: [ 1.5986328125, 1.09375, 0.7978515625 ],
     uptime: 277082 },
  trace: 
   [ { column: 11,
       file: 'net.js',
       function: 'Socket.write',
       line: 654,
       method: 'write',
       native: false },
     { column: 21,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 457,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.read',
       line: 381,
       method: 'read',
       native: false },
     { column: 15,
       file: 'net.js',
       function: 'Socket.read',
       line: 308,
       method: 'read',
       native: false },
     { column: 34,
       file: '_stream_readable.js',
       function: 'flow',
       line: 761,
       method: null,
       native: false },
     { column: 3,
       file: '_stream_readable.js',
       function: 'resume_',
       line: 743,
       method: null,
       native: false },
     { column: 11,
       file: 'internal/process/next_tick.js',
       function: '_combinedTickCallback',
       line: 80,
       method: null,
       native: false },
     { column: 9,
       file: 'internal/process/next_tick.js',
       function: 'process._tickCallback',
       line: 104,
       method: '_tickCallback',
       native: false } ],
  stack: 
   [ 'TypeError: Invalid data, chunk must be a string or buffer, not number',
     '    at Socket.write (net.js:654:11)',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:457:21)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at Socket.Readable.read (_stream_readable.js:381:10)',
     '    at Socket.read (net.js:308:15)',
     '    at flow (_stream_readable.js:761:34)',
     '    at resume_ (_stream_readable.js:743:3)',
     '    at _combinedTickCallback (internal/process/next_tick.js:80:11)',
     '    at process._tickCallback (internal/process/next_tick.js:104:9)' ] }
17/11/18 05:29:35.539 [pid:223] - error: uncaughtException: write after end 
{ date: 'Sat Nov 18 2017 05:29:35 GMT+0000 (UTC)',
  process: 
   { pid: 223,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 67952640,
        heapTotal: 45944832,
        heapUsed: 38276904,
        external: 18003217 } },
  os: 
   { loadavg: [ 0.498046875, 0.84033203125, 0.734375 ],
     uptime: 277188 },
  trace: 
   [ { column: 12,
       file: '_stream_writable.js',
       function: 'writeAfterEnd',
       line: 193,
       method: null,
       native: false },
     { column: 5,
       file: '_stream_writable.js',
       function: 'Socket.Writable.write',
       line: 240,
       method: 'write',
       native: false },
     { column: 40,
       file: 'net.js',
       function: 'Socket.write',
       line: 657,
       method: 'write',
       native: false },
     { column: 21,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 457,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: write after end',
     '    at writeAfterEnd (_stream_writable.js:193:12)',
     '    at Socket.Writable.write (_stream_writable.js:240:5)',
     '    at Socket.write (net.js:657:40)',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:457:21)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 05:36:19.548 [pid:245] - error: uncaughtException: write after end 
{ date: 'Sat Nov 18 2017 05:36:19 GMT+0000 (UTC)',
  process: 
   { pid: 245,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 72003584,
        heapTotal: 65867776,
        heapUsed: 36703904,
        external: 19414485 } },
  os: 
   { loadavg: [ 0.0986328125, 0.39794921875, 0.56103515625 ],
     uptime: 277593 },
  trace: 
   [ { column: 12,
       file: '_stream_writable.js',
       function: 'writeAfterEnd',
       line: 193,
       method: null,
       native: false },
     { column: 5,
       file: '_stream_writable.js',
       function: 'Socket.Writable.write',
       line: 240,
       method: 'write',
       native: false },
     { column: 40,
       file: 'net.js',
       function: 'Socket.write',
       line: 657,
       method: 'write',
       native: false },
     { column: 21,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 457,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: write after end',
     '    at writeAfterEnd (_stream_writable.js:193:12)',
     '    at Socket.Writable.write (_stream_writable.js:240:5)',
     '    at Socket.write (net.js:657:40)',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:457:21)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 05:39:57.250 [pid:263] - error: uncaughtException: Cannot read property 'length' of undefined 
{ date: 'Sat Nov 18 2017 05:39:57 GMT+0000 (UTC)',
  process: 
   { pid: 263,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 85319680,
        heapTotal: 70062080,
        heapUsed: 37073640,
        external: 18000894 } },
  os: 
   { loadavg: [ 0.23095703125, 0.2958984375, 0.48095703125 ],
     uptime: 277810 },
  trace: 
   [ { column: 20,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 455,
       method: null,
       native: false },
     { column: 3,
       file: 'fs.js',
       function: 'tryToString',
       line: 456,
       method: null,
       native: false },
     { column: 12,
       file: 'fs.js',
       function: 'FSReqWrap.readFileAfterClose [as oncomplete]',
       line: 443,
       method: 'readFileAfterClose [as oncomplete]',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'length\' of undefined',
     '    at /workspace/Assignment/server/controllers/fileManager.js:455:20',
     '    at tryToString (fs.js:456:3)',
     '    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)' ] }
17/11/18 05:56:22.652 [pid:285] - error: uncaughtException: Cannot read property 'length' of undefined 
{ date: 'Sat Nov 18 2017 05:56:22 GMT+0000 (UTC)',
  process: 
   { pid: 285,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 85282816,
        heapTotal: 70062080,
        heapUsed: 36848856,
        external: 17976318 } },
  os: 
   { loadavg: [ 0.1474609375, 0.1474609375, 0.2587890625 ],
     uptime: 278796 },
  trace: 
   [ { column: 20,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 455,
       method: null,
       native: false },
     { column: 3,
       file: 'fs.js',
       function: 'tryToString',
       line: 456,
       method: null,
       native: false },
     { column: 12,
       file: 'fs.js',
       function: 'FSReqWrap.readFileAfterClose [as oncomplete]',
       line: 443,
       method: 'readFileAfterClose [as oncomplete]',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'length\' of undefined',
     '    at /workspace/Assignment/server/controllers/fileManager.js:455:20',
     '    at tryToString (fs.js:456:3)',
     '    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)' ] }
17/11/18 07:12:29.771 [pid:114] - error: uncaughtException: listen EADDRINUSE :::3000 
{ date: 'Sat Nov 18 2017 07:12:29 GMT+0000 (UTC)',
  process: 
   { pid: 114,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 69234688,
        heapTotal: 63770624,
        heapUsed: 34057096,
        external: 19370729 } },
  os: 
   { loadavg: [ 1.79638671875, 1.33447265625, 1.265625 ],
     uptime: 283256 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'Object.exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 20,
       file: 'util.js',
       function: 'exports._exceptionWithHostPort',
       line: 1041,
       method: '_exceptionWithHostPort',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'Server._listen2',
       line: 1258,
       method: '_listen2',
       native: false },
     { column: 10,
       file: 'net.js',
       function: 'listen',
       line: 1294,
       method: null,
       native: false },
     { column: 5,
       file: 'net.js',
       function: 'Server.listen',
       line: 1390,
       method: 'listen',
       native: false },
     { column: 44,
       file: '/workspace/Assignment/server/server2.js',
       function: null,
       line: 264,
       method: null,
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module._compile',
       line: 570,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Module._extensions..js',
       line: 579,
       method: '.js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 487,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 446,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Module._load',
       line: 438,
       method: '_load',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Module.runMain',
       line: 604,
       method: 'runMain',
       native: false },
     { column: 7,
       file: 'bootstrap_node.js',
       function: 'run',
       line: 389,
       method: null,
       native: false },
     { column: 9,
       file: 'bootstrap_node.js',
       function: 'startup',
       line: 149,
       method: null,
       native: false },
     { column: 3,
       file: 'bootstrap_node.js',
       function: null,
       line: 504,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: listen EADDRINUSE :::3000',
     '    at Object.exports._errnoException (util.js:1018:11)',
     '    at exports._exceptionWithHostPort (util.js:1041:20)',
     '    at Server._listen2 (net.js:1258:14)',
     '    at listen (net.js:1294:10)',
     '    at Server.listen (net.js:1390:5)',
     '    at Object.<anonymous> (/workspace/Assignment/server/server2.js:264:44)',
     '    at Module._compile (module.js:570:32)',
     '    at Object.Module._extensions..js (module.js:579:10)',
     '    at Module.load (module.js:487:32)',
     '    at tryModuleLoad (module.js:446:12)',
     '    at Function.Module._load (module.js:438:3)',
     '    at Module.runMain (module.js:604:10)',
     '    at run (bootstrap_node.js:389:7)',
     '    at startup (bootstrap_node.js:149:9)',
     '    at bootstrap_node.js:504:3' ] }
17/11/18 07:14:04.009 [pid:136] - error: uncaughtException: listen EADDRINUSE :::3000 
{ date: 'Sat Nov 18 2017 07:14:03 GMT+0000 (UTC)',
  process: 
   { pid: 136,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 69509120,
        heapTotal: 64819200,
        heapUsed: 34013200,
        external: 19396952 } },
  os: 
   { loadavg: [ 0.9267578125, 1.24365234375, 1.24365234375 ],
     uptime: 283350 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'Object.exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 20,
       file: 'util.js',
       function: 'exports._exceptionWithHostPort',
       line: 1041,
       method: '_exceptionWithHostPort',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'Server._listen2',
       line: 1258,
       method: '_listen2',
       native: false },
     { column: 10,
       file: 'net.js',
       function: 'listen',
       line: 1294,
       method: null,
       native: false },
     { column: 5,
       file: 'net.js',
       function: 'Server.listen',
       line: 1390,
       method: 'listen',
       native: false },
     { column: 44,
       file: '/workspace/Assignment/server/server2.js',
       function: null,
       line: 262,
       method: null,
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module._compile',
       line: 570,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Module._extensions..js',
       line: 579,
       method: '.js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 487,
       method: 'load',
       native: false },
     { column: 12,
       file: 'module.js',
       function: 'tryModuleLoad',
       line: 446,
       method: null,
       native: false },
     { column: 3,
       file: 'module.js',
       function: 'Module._load',
       line: 438,
       method: '_load',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Module.runMain',
       line: 604,
       method: 'runMain',
       native: false },
     { column: 7,
       file: 'bootstrap_node.js',
       function: 'run',
       line: 389,
       method: null,
       native: false },
     { column: 9,
       file: 'bootstrap_node.js',
       function: 'startup',
       line: 149,
       method: null,
       native: false },
     { column: 3,
       file: 'bootstrap_node.js',
       function: null,
       line: 504,
       method: null,
       native: false } ],
  stack: 
   [ 'Error: listen EADDRINUSE :::3000',
     '    at Object.exports._errnoException (util.js:1018:11)',
     '    at exports._exceptionWithHostPort (util.js:1041:20)',
     '    at Server._listen2 (net.js:1258:14)',
     '    at listen (net.js:1294:10)',
     '    at Server.listen (net.js:1390:5)',
     '    at Object.<anonymous> (/workspace/Assignment/server/server2.js:262:44)',
     '    at Module._compile (module.js:570:32)',
     '    at Object.Module._extensions..js (module.js:579:10)',
     '    at Module.load (module.js:487:32)',
     '    at tryModuleLoad (module.js:446:12)',
     '    at Function.Module._load (module.js:438:3)',
     '    at Module.runMain (module.js:604:10)',
     '    at run (bootstrap_node.js:389:7)',
     '    at startup (bootstrap_node.js:149:9)',
     '    at bootstrap_node.js:504:3' ] }
17/11/18 07:18:20.030 [pid:270] - error: uncaughtException: count is not defined 
{ date: 'Sat Nov 18 2017 07:18:20 GMT+0000 (UTC)',
  process: 
   { pid: 270,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 85495808,
        heapTotal: 70062080,
        heapUsed: 37364288,
        external: 18051046 } },
  os: 
   { loadavg: [ 1.26318359375, 1.1728515625, 1.19384765625 ],
     uptime: 283606 },
  trace: 
   [ { column: 27,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 467,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'ReferenceError: count is not defined',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:467:27)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 07:20:04.530 [pid:291] - error: uncaughtException: write after end 
{ date: 'Sat Nov 18 2017 07:20:04 GMT+0000 (UTC)',
  process: 
   { pid: 291,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 88825856,
        heapTotal: 70062080,
        heapUsed: 37554624,
        external: 17969064 } },
  os: 
   { loadavg: [ 1.6875, 1.4013671875, 1.27734375 ],
     uptime: 283711 },
  trace: 
   [ { column: 12,
       file: '_stream_writable.js',
       function: 'writeAfterEnd',
       line: 193,
       method: null,
       native: false },
     { column: 5,
       file: '_stream_writable.js',
       function: 'Socket.Writable.write',
       line: 240,
       method: 'write',
       native: false },
     { column: 40,
       file: 'net.js',
       function: 'Socket.write',
       line: 657,
       method: 'write',
       native: false },
     { column: 19,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 468,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: write after end',
     '    at writeAfterEnd (_stream_writable.js:193:12)',
     '    at Socket.Writable.write (_stream_writable.js:240:5)',
     '    at Socket.write (net.js:657:40)',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:468:19)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 07:22:47.627 [pid:313] - error: uncaughtException: write after end 
{ date: 'Sat Nov 18 2017 07:22:47 GMT+0000 (UTC)',
  process: 
   { pid: 313,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 87564288,
        heapTotal: 70062080,
        heapUsed: 37345600,
        external: 17977357 } },
  os: 
   { loadavg: [ 0.95458984375, 1.30712890625, 1.2685546875 ],
     uptime: 283874 },
  trace: 
   [ { column: 12,
       file: '_stream_writable.js',
       function: 'writeAfterEnd',
       line: 193,
       method: null,
       native: false },
     { column: 5,
       file: '_stream_writable.js',
       function: 'Socket.Writable.write',
       line: 240,
       method: 'write',
       native: false },
     { column: 40,
       file: 'net.js',
       function: 'Socket.write',
       line: 657,
       method: 'write',
       native: false },
     { column: 19,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 468,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: write after end',
     '    at writeAfterEnd (_stream_writable.js:193:12)',
     '    at Socket.Writable.write (_stream_writable.js:240:5)',
     '    at Socket.write (net.js:657:40)',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:468:19)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 07:23:29.017 [pid:335] - error: uncaughtException: write EPIPE 
{ date: 'Sat Nov 18 2017 07:23:28 GMT+0000 (UTC)',
  process: 
   { pid: 335,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 86953984,
        heapTotal: 70062080,
        heapUsed: 37503992,
        external: 17985549 } },
  os: 
   { loadavg: [ 0.541015625, 1.15673828125, 1.21923828125 ],
     uptime: 283915 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'WriteWrap.afterWrite',
       line: 800,
       method: 'afterWrite',
       native: false } ],
  stack: 
   [ 'Error: write EPIPE',
     '    at exports._errnoException (util.js:1018:11)',
     '    at WriteWrap.afterWrite (net.js:800:14)' ] }
17/11/18 07:29:24.526 [pid:357] - error: uncaughtException: write EPIPE 
{ date: 'Sat Nov 18 2017 07:29:24 GMT+0000 (UTC)',
  process: 
   { pid: 357,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 68018176,
        heapTotal: 44896256,
        heapUsed: 37631832,
        external: 17985418 } },
  os: 
   { loadavg: [ 0.49169921875, 0.78955078125, 1.0263671875 ],
     uptime: 284271 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'WriteWrap.afterWrite',
       line: 800,
       method: 'afterWrite',
       native: false } ],
  stack: 
   [ 'Error: write EPIPE',
     '    at exports._errnoException (util.js:1018:11)',
     '    at WriteWrap.afterWrite (net.js:800:14)' ] }
17/11/18 07:30:59.223 [pid:379] - error: uncaughtException: write EPIPE 
{ date: 'Sat Nov 18 2017 07:30:59 GMT+0000 (UTC)',
  process: 
   { pid: 379,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 92704768,
        heapTotal: 70062080,
        heapUsed: 37178912,
        external: 17977125 } },
  os: 
   { loadavg: [ 0.19189453125, 0.60107421875, 0.93359375 ],
     uptime: 284365 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'WriteWrap.afterWrite',
       line: 800,
       method: 'afterWrite',
       native: false } ],
  stack: 
   [ 'Error: write EPIPE',
     '    at exports._errnoException (util.js:1018:11)',
     '    at WriteWrap.afterWrite (net.js:800:14)' ] }
17/11/18 07:33:10.316 [pid:401] - error: uncaughtException: write after end 
{ date: 'Sat Nov 18 2017 07:33:10 GMT+0000 (UTC)',
  process: 
   { pid: 401,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 85692416,
        heapTotal: 70062080,
        heapUsed: 38497168,
        external: 18009006 } },
  os: 
   { loadavg: [ 1.04833984375, 0.7744140625, 0.95263671875 ],
     uptime: 284496 },
  trace: 
   [ { column: 12,
       file: '_stream_writable.js',
       function: 'writeAfterEnd',
       line: 193,
       method: null,
       native: false },
     { column: 5,
       file: '_stream_writable.js',
       function: 'Socket.Writable.write',
       line: 240,
       method: 'write',
       native: false },
     { column: 40,
       file: 'net.js',
       function: 'Socket.write',
       line: 657,
       method: 'write',
       native: false },
     { column: 18,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 467,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: write after end',
     '    at writeAfterEnd (_stream_writable.js:193:12)',
     '    at Socket.Writable.write (_stream_writable.js:240:5)',
     '    at Socket.write (net.js:657:40)',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:467:18)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 07:35:59.715 [pid:423] - error: uncaughtException: write after end 
{ date: 'Sat Nov 18 2017 07:35:59 GMT+0000 (UTC)',
  process: 
   { pid: 423,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 85065728,
        heapTotal: 70062080,
        heapUsed: 37455752,
        external: 17977086 } },
  os: 
   { loadavg: [ 1.9453125, 1.09423828125, 1.0283203125 ],
     uptime: 284666 },
  trace: 
   [ { column: 12,
       file: '_stream_writable.js',
       function: 'writeAfterEnd',
       line: 193,
       method: null,
       native: false },
     { column: 5,
       file: '_stream_writable.js',
       function: 'Socket.Writable.write',
       line: 240,
       method: 'write',
       native: false },
     { column: 40,
       file: 'net.js',
       function: 'Socket.write',
       line: 657,
       method: 'write',
       native: false },
     { column: 20,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 472,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: write after end',
     '    at writeAfterEnd (_stream_writable.js:193:12)',
     '    at Socket.Writable.write (_stream_writable.js:240:5)',
     '    at Socket.write (net.js:657:40)',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:472:20)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 07:36:49.711 [pid:445] - error: uncaughtException: write EPIPE 
{ date: 'Sat Nov 18 2017 07:36:49 GMT+0000 (UTC)',
  process: 
   { pid: 445,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 87334912,
        heapTotal: 70062080,
        heapUsed: 38140264,
        external: 17991106 } },
  os: 
   { loadavg: [ 1.51953125, 1.09765625, 1.02978515625 ],
     uptime: 284716 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'WriteWrap.afterWrite',
       line: 800,
       method: 'afterWrite',
       native: false } ],
  stack: 
   [ 'Error: write EPIPE',
     '    at exports._errnoException (util.js:1018:11)',
     '    at WriteWrap.afterWrite (net.js:800:14)' ] }
17/11/18 08:16:46.609 [pid:628] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 08:16:46 GMT+0000 (UTC)',
  process: 
   { pid: 628,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 71790592,
        heapTotal: 65867776,
        heapUsed: 37120728,
        external: 19373283 } },
  os: 
   { loadavg: [ 0.38330078125, 0.6826171875, 0.81103515625 ],
     uptime: 287113 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 6,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 477,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:477:6)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 08:37:17.920 [pid:686] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 08:37:17 GMT+0000 (UTC)',
  process: 
   { pid: 686,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 85639168,
        heapTotal: 70062080,
        heapUsed: 37708736,
        external: 17960741 } },
  os: 
   { loadavg: [ 0.3916015625, 0.33544921875, 0.44091796875 ],
     uptime: 288344 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 493,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:493:7)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 08:56:15.495 [pid:708] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 08:56:15 GMT+0000 (UTC)',
  process: 
   { pid: 708,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 86646784,
        heapTotal: 70062080,
        heapUsed: 37247352,
        external: 17985347 } },
  os: 
   { loadavg: [ 0.19580078125, 0.24609375, 0.31005859375 ],
     uptime: 289482 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 493,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:493:7)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 09:00:54.412 [pid:730] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 09:00:54 GMT+0000 (UTC)',
  process: 
   { pid: 730,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 86364160,
        heapTotal: 70062080,
        heapUsed: 37525352,
        external: 17992751 } },
  os: 
   { loadavg: [ 0.1767578125, 0.1953125, 0.263671875 ],
     uptime: 289760 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 8,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 492,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:492:8)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 09:22:54.008 [pid:774] - error: uncaughtException: write after end 
{ date: 'Sat Nov 18 2017 09:22:54 GMT+0000 (UTC)',
  process: 
   { pid: 774,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 89485312,
        heapTotal: 70062080,
        heapUsed: 37073608,
        external: 17960640 } },
  os: 
   { loadavg: [ 0.2060546875, 0.21533203125, 0.24169921875 ],
     uptime: 291080 },
  trace: 
   [ { column: 12,
       file: '_stream_writable.js',
       function: 'writeAfterEnd',
       line: 193,
       method: null,
       native: false },
     { column: 5,
       file: '_stream_writable.js',
       function: 'Socket.Writable.write',
       line: 240,
       method: 'write',
       native: false },
     { column: 40,
       file: 'net.js',
       function: 'Socket.write',
       line: 657,
       method: 'write',
       native: false },
     { column: 20,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 484,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: write after end',
     '    at writeAfterEnd (_stream_writable.js:193:12)',
     '    at Socket.Writable.write (_stream_writable.js:240:5)',
     '    at Socket.write (net.js:657:40)',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:484:20)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:03:09.522 [pid:870] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:03:09 GMT+0000 (UTC)',
  process: 
   { pid: 870,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 68784128,
        heapTotal: 38604800,
        heapUsed: 31408312,
        external: 17985136 } },
  os: 
   { loadavg: [ 0.32666015625, 0.25146484375, 0.21142578125 ],
     uptime: 293496 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 440,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:440:14)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:03:09.610 [pid:870] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:03:09 GMT+0000 (UTC)',
  process: 
   { pid: 870,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 68554752,
        heapTotal: 38604800,
        heapUsed: 31239184,
        external: 17983333 } },
  os: 
   { loadavg: [ 0.32666015625, 0.25146484375, 0.21142578125 ],
     uptime: 293496 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 440,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:440:14)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:06:17.921 [pid:910] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:06:17 GMT+0000 (UTC)',
  process: 
   { pid: 910,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 73379840,
        heapTotal: 65867776,
        heapUsed: 37820912,
        external: 19422295 } },
  os: 
   { loadavg: [ 0.05908203125, 0.18310546875, 0.1865234375 ],
     uptime: 293684 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 440,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:440:14)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:07:37.703 [pid:928] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:07:37 GMT+0000 (UTC)',
  process: 
   { pid: 928,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 91455488,
        heapTotal: 70062080,
        heapUsed: 37250512,
        external: 17993565 } },
  os: 
   { loadavg: [ 0.22998046875, 0.18701171875, 0.185546875 ],
     uptime: 293764 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 440,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:440:14)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:20:26.814 [pid:949] - error: uncaughtException: spawn EACCES 
{ date: 'Sat Nov 18 2017 10:20:26 GMT+0000 (UTC)',
  process: 
   { pid: 949,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 65069056,
        heapTotal: 38604800,
        heapUsed: 31359056,
        external: 17985035 } },
  os: 
   { loadavg: [ 0.302734375, 0.25390625, 0.2109375 ],
     uptime: 294533 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 11,
       file: 'internal/child_process.js',
       function: 'ChildProcess.spawn',
       line: 319,
       method: 'spawn',
       native: false },
     { column: 9,
       file: 'child_process.js',
       function: 'exports.spawn',
       line: 378,
       method: 'spawn',
       native: false },
     { column: 13,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'async.waterfall.result',
       line: 457,
       method: 'result',
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: 'nextTask',
       line: 5310,
       method: null,
       native: false },
     { column: 9,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: 'next',
       line: 5317,
       method: null,
       native: false },
     { column: 16,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 958,
       method: null,
       native: false },
     { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'Timeout._onTimeout',
       line: 450,
       method: '_onTimeout',
       native: false },
     { column: 14,
       file: 'timers.js',
       function: 'ontimeout',
       line: 386,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'tryOnTimeout',
       line: 250,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'Timer.listOnTimeout',
       line: 214,
       method: 'listOnTimeout',
       native: false } ],
  stack: 
   [ 'Error: spawn EACCES',
     '    at exports._errnoException (util.js:1018:11)',
     '    at ChildProcess.spawn (internal/child_process.js:319:11)',
     '    at exports.spawn (child_process.js:378:9)',
     '    at async.waterfall.result (/workspace/Assignment/server/controllers/fileManager.js:457:13)',
     '    at nextTask (/workspace/Assignment/server/node_modules/async/dist/async.js:5310:14)',
     '    at next (/workspace/Assignment/server/node_modules/async/dist/async.js:5317:9)',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:958:16',
     '    at Timeout._onTimeout (/workspace/Assignment/server/controllers/fileManager.js:450:7)',
     '    at ontimeout (timers.js:386:14)',
     '    at tryOnTimeout (timers.js:250:5)',
     '    at Timer.listOnTimeout (timers.js:214:5)' ] }
17/11/18 10:21:29.313 [pid:1011] - error: uncaughtException: Cannot read property 'length' of null 
{ date: 'Sat Nov 18 2017 10:21:29 GMT+0000 (UTC)',
  process: 
   { pid: 1011,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 74424320,
        heapTotal: 65867776,
        heapUsed: 37623088,
        external: 19387786 } },
  os: 
   { loadavg: [ 0.22802734375, 0.23388671875, 0.20361328125 ],
     uptime: 294595 },
  trace: 
   [ { column: 19,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 484,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'length\' of null',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:484:19)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:23:40.121 [pid:1029] - error: uncaughtException: Cannot read property 'length' of null 
{ date: 'Sat Nov 18 2017 10:23:40 GMT+0000 (UTC)',
  process: 
   { pid: 1029,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 87519232,
        heapTotal: 70062080,
        heapUsed: 36875680,
        external: 17968356 } },
  os: 
   { loadavg: [ 0.28369140625, 0.24658203125, 0.20654296875 ],
     uptime: 294726 },
  trace: 
   [ { column: 19,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 487,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'length\' of null',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:487:19)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:25:13.777 [pid:1051] - error: uncaughtException: Cannot read property 'length' of null 
{ date: 'Sat Nov 18 2017 10:25:13 GMT+0000 (UTC)',
  process: 
   { pid: 1051,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 71630848,
        heapTotal: 65867776,
        heapUsed: 37036848,
        external: 19373725 } },
  os: 
   { loadavg: [ 0.45458984375, 0.30078125, 0.22705078125 ],
     uptime: 294820 },
  trace: 
   [ { column: 19,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 487,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'length\' of null',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:487:19)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:31:17.230 [pid:1069] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:31:17 GMT+0000 (UTC)',
  process: 
   { pid: 1069,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 63811584,
        heapTotal: 37556224,
        heapUsed: 30301944,
        external: 17932415 } },
  os: 
   { loadavg: [ 0.11962890625, 0.17578125, 0.1845703125 ],
     uptime: 295183 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 440,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:440:14)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:33:48.029 [pid:1108] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:33:48 GMT+0000 (UTC)',
  process: 
   { pid: 1108,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 91156480,
        heapTotal: 70062080,
        heapUsed: 37071072,
        external: 18039265 } },
  os: 
   { loadavg: [ 0.31591796875, 0.23388671875, 0.19873046875 ],
     uptime: 295334 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 440,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:440:14)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:33:48.112 [pid:1108] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:33:48 GMT+0000 (UTC)',
  process: 
   { pid: 1108,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 91250688,
        heapTotal: 70062080,
        heapUsed: 37706376,
        external: 18047457 } },
  os: 
   { loadavg: [ 0.31591796875, 0.23388671875, 0.19873046875 ],
     uptime: 295334 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'Timeout._onTimeout',
       line: 450,
       method: '_onTimeout',
       native: false },
     { column: 14,
       file: 'timers.js',
       function: 'ontimeout',
       line: 386,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'tryOnTimeout',
       line: 250,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'Timer.listOnTimeout',
       line: 214,
       method: 'listOnTimeout',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Timeout._onTimeout (/workspace/Assignment/server/controllers/fileManager.js:450:7)',
     '    at ontimeout (timers.js:386:14)',
     '    at tryOnTimeout (timers.js:250:5)',
     '    at Timer.listOnTimeout (timers.js:214:5)' ] }
17/11/18 10:35:56.412 [pid:1129] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:35:56 GMT+0000 (UTC)',
  process: 
   { pid: 1129,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 84684800,
        heapTotal: 70062080,
        heapUsed: 37293480,
        external: 17963782 } },
  os: 
   { loadavg: [ 0.224609375, 0.21630859375, 0.18994140625 ],
     uptime: 295462 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 441,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:441:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:35:56.422 [pid:1129] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:35:56 GMT+0000 (UTC)',
  process: 
   { pid: 1129,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 84779008,
        heapTotal: 70062080,
        heapUsed: 37930448,
        external: 17965011 } },
  os: 
   { loadavg: [ 0.224609375, 0.21630859375, 0.18994140625 ],
     uptime: 295463 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 441,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:441:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:38:10.133 [pid:1151] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:38:10 GMT+0000 (UTC)',
  process: 
   { pid: 1151,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 89657344,
        heapTotal: 70062080,
        heapUsed: 37176496,
        external: 17997439 } },
  os: 
   { loadavg: [ 0.25390625, 0.2294921875, 0.19140625 ],
     uptime: 295596 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 441,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:441:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:38:10.214 [pid:1151] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:38:10 GMT+0000 (UTC)',
  process: 
   { pid: 1151,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 89743360,
        heapTotal: 70062080,
        heapUsed: 37813264,
        external: 17998668 } },
  os: 
   { loadavg: [ 0.25390625, 0.2294921875, 0.19140625 ],
     uptime: 295596 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 441,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:441:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:41:54.230 [pid:1173] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:41:54 GMT+0000 (UTC)',
  process: 
   { pid: 1173,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 88895488,
        heapTotal: 70062080,
        heapUsed: 38067984,
        external: 17989166 } },
  os: 
   { loadavg: [ 0.14501953125, 0.20361328125, 0.1806640625 ],
     uptime: 295820 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 441,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:441:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:41:54.234 [pid:1173] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:41:54 GMT+0000 (UTC)',
  process: 
   { pid: 1173,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 88985600,
        heapTotal: 70062080,
        heapUsed: 38703296,
        external: 17989800 } },
  os: 
   { loadavg: [ 0.14501953125, 0.20361328125, 0.1806640625 ],
     uptime: 295820 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 441,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:441:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:43:59.810 [pid:1194] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:43:59 GMT+0000 (UTC)',
  process: 
   { pid: 1194,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 89645056,
        heapTotal: 70062080,
        heapUsed: 37946976,
        external: 17973460 } },
  os: 
   { loadavg: [ 0.3955078125, 0.23828125, 0.1953125 ],
     uptime: 295946 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 438,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:438:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:45:16.309 [pid:1215] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:45:16 GMT+0000 (UTC)',
  process: 
   { pid: 1215,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 85037056,
        heapTotal: 70062080,
        heapUsed: 37466632,
        external: 18003288 } },
  os: 
   { loadavg: [ 0.375, 0.25732421875, 0.201171875 ],
     uptime: 296022 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 438,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:438:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:51:18.533 [pid:1233] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:51:18 GMT+0000 (UTC)',
  process: 
   { pid: 1233,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 88014848,
        heapTotal: 70062080,
        heapUsed: 37597952,
        external: 17961439 } },
  os: 
   { loadavg: [ 0.30029296875, 0.2705078125, 0.2177734375 ],
     uptime: 296385 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 15,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 441,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:441:15)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:56:34.140 [pid:1251] - error: uncaughtException: Callback was already called. 
{ date: 'Sat Nov 18 2017 10:56:34 GMT+0000 (UTC)',
  process: 
   { pid: 1251,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 88891392,
        heapTotal: 70062080,
        heapUsed: 37023184,
        external: 18026975 } },
  os: 
   { loadavg: [ 0.15966796875, 0.21533203125, 0.19580078125 ],
     uptime: 296700 },
  trace: 
   [ { column: 32,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 955,
       method: null,
       native: false },
     { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 441,
       method: null,
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitOne',
       line: 96,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Socket.emit',
       line: 188,
       method: 'emit',
       native: false },
     { column: 18,
       file: '_stream_readable.js',
       function: 'readableAddChunk',
       line: 176,
       method: null,
       native: false },
     { column: 10,
       file: '_stream_readable.js',
       function: 'Socket.Readable.push',
       line: 134,
       method: 'push',
       native: false },
     { column: 20,
       file: 'net.js',
       function: 'Pipe.onread',
       line: 547,
       method: 'onread',
       native: false } ],
  stack: 
   [ 'Error: Callback was already called.',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:955:32',
     '    at Socket.<anonymous> (/workspace/Assignment/server/controllers/fileManager.js:441:7)',
     '    at emitOne (events.js:96:13)',
     '    at Socket.emit (events.js:188:7)',
     '    at readableAddChunk (_stream_readable.js:176:18)',
     '    at Socket.Readable.push (_stream_readable.js:134:10)',
     '    at Pipe.onread (net.js:547:20)' ] }
17/11/18 10:57:51.649 [pid:1269] - error: uncaughtException: callback is not a function 
{ date: 'Sat Nov 18 2017 10:57:51 GMT+0000 (UTC)',
  process: 
   { pid: 1269,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 91463680,
        heapTotal: 70062080,
        heapUsed: 43862176,
        external: 18049989 } },
  os: 
   { loadavg: [ 0.13671875, 0.19189453125, 0.18359375 ],
     uptime: 296778 },
  trace: 
   [ { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'Timeout._onTimeout',
       line: 500,
       method: '_onTimeout',
       native: false },
     { column: 14,
       file: 'timers.js',
       function: 'ontimeout',
       line: 386,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'tryOnTimeout',
       line: 250,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'Timer.listOnTimeout',
       line: 214,
       method: 'listOnTimeout',
       native: false } ],
  stack: 
   [ 'TypeError: callback is not a function',
     '    at Timeout._onTimeout (/workspace/Assignment/server/controllers/fileManager.js:500:7)',
     '    at ontimeout (timers.js:386:14)',
     '    at tryOnTimeout (timers.js:250:5)',
     '    at Timer.listOnTimeout (timers.js:214:5)' ] }
17/11/18 11:01:03.280 [pid:1288] - error: uncaughtException: callback is not a function 
{ date: 'Sat Nov 18 2017 11:01:03 GMT+0000 (UTC)',
  process: 
   { pid: 1288,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 91525120,
        heapTotal: 70062080,
        heapUsed: 37276128,
        external: 17986247 } },
  os: 
   { loadavg: [ 0.08544921875, 0.1455078125, 0.1689453125 ],
     uptime: 296969 },
  trace: 
   [ { column: 6,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'async.waterfall.result',
       line: 502,
       method: 'result',
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: 'nextTask',
       line: 5310,
       method: null,
       native: false },
     { column: 9,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: 'next',
       line: 5317,
       method: null,
       native: false },
     { column: 16,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 958,
       method: null,
       native: false },
     { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'Timeout._onTimeout',
       line: 474,
       method: '_onTimeout',
       native: false },
     { column: 14,
       file: 'timers.js',
       function: 'ontimeout',
       line: 386,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'tryOnTimeout',
       line: 250,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'Timer.listOnTimeout',
       line: 214,
       method: 'listOnTimeout',
       native: false } ],
  stack: 
   [ 'TypeError: callback is not a function',
     '    at async.waterfall.result (/workspace/Assignment/server/controllers/fileManager.js:502:6)',
     '    at nextTask (/workspace/Assignment/server/node_modules/async/dist/async.js:5310:14)',
     '    at next (/workspace/Assignment/server/node_modules/async/dist/async.js:5317:9)',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:958:16',
     '    at Timeout._onTimeout (/workspace/Assignment/server/controllers/fileManager.js:474:7)',
     '    at ontimeout (timers.js:386:14)',
     '    at tryOnTimeout (timers.js:250:5)',
     '    at Timer.listOnTimeout (timers.js:214:5)' ] }
17/11/18 11:10:25.627 [pid:1357] - error: uncaughtException: spawn EACCES 
{ date: 'Sat Nov 18 2017 11:10:25 GMT+0000 (UTC)',
  process: 
   { pid: 1357,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 64069632,
        heapTotal: 38604800,
        heapUsed: 31484568,
        external: 18002121 } },
  os: 
   { loadavg: [ 0.11767578125, 0.2275390625, 0.220703125 ],
     uptime: 297532 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 11,
       file: 'internal/child_process.js',
       function: 'ChildProcess.spawn',
       line: 319,
       method: 'spawn',
       native: false },
     { column: 9,
       file: 'child_process.js',
       function: 'exports.spawn',
       line: 378,
       method: 'spawn',
       native: false },
     { column: 14,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'Timeout._onTimeout',
       line: 457,
       method: '_onTimeout',
       native: false },
     { column: 14,
       file: 'timers.js',
       function: 'ontimeout',
       line: 386,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'tryOnTimeout',
       line: 250,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'Timer.listOnTimeout',
       line: 214,
       method: 'listOnTimeout',
       native: false } ],
  stack: 
   [ 'Error: spawn EACCES',
     '    at exports._errnoException (util.js:1018:11)',
     '    at ChildProcess.spawn (internal/child_process.js:319:11)',
     '    at exports.spawn (child_process.js:378:9)',
     '    at Timeout._onTimeout (/workspace/Assignment/server/controllers/fileManager.js:457:14)',
     '    at ontimeout (timers.js:386:14)',
     '    at tryOnTimeout (timers.js:250:5)',
     '    at Timer.listOnTimeout (timers.js:214:5)' ] }
17/11/18 11:16:53.222 [pid:1394] - error: uncaughtException: Cannot read property 'toString' of null 
{ date: 'Sat Nov 18 2017 11:16:53 GMT+0000 (UTC)',
  process: 
   { pid: 1394,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 66633728,
        heapTotal: 38604800,
        heapUsed: 31227800,
        external: 18068572 } },
  os: 
   { loadavg: [ 0.71240234375, 0.46923828125, 0.32373046875 ],
     uptime: 297919 },
  trace: 
   [ { column: 83,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 521,
       method: null,
       native: false },
     { column: 16,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 473,
       method: null,
       native: false },
     { column: 29,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: 'next',
       line: 5315,
       method: null,
       native: false },
     { column: 16,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 958,
       method: null,
       native: false },
     { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'Timeout._onTimeout',
       line: 504,
       method: '_onTimeout',
       native: false },
     { column: 14,
       file: 'timers.js',
       function: 'ontimeout',
       line: 386,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'tryOnTimeout',
       line: 250,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'Timer.listOnTimeout',
       line: 214,
       method: 'listOnTimeout',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'toString\' of null',
     '    at /workspace/Assignment/server/controllers/fileManager.js:521:83',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:473:16',
     '    at next (/workspace/Assignment/server/node_modules/async/dist/async.js:5315:29)',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:958:16',
     '    at Timeout._onTimeout (/workspace/Assignment/server/controllers/fileManager.js:504:7)',
     '    at ontimeout (timers.js:386:14)',
     '    at tryOnTimeout (timers.js:250:5)',
     '    at Timer.listOnTimeout (timers.js:214:5)' ] }
17/11/18 11:19:42.820 [pid:1458] - error: uncaughtException: Cannot read property 'toString' of null 
{ date: 'Sat Nov 18 2017 11:19:42 GMT+0000 (UTC)',
  process: 
   { pid: 1458,
     uid: 0,
     gid: 0,
     cwd: '/workspace/Assignment',
     execPath: '/usr/bin/nodejs',
     version: 'v6.11.0',
     argv: [ '/usr/bin/nodejs', '/workspace/Assignment/server/server2.js' ],
     memoryUsage: 
      { rss: 77176832,
        heapTotal: 67964928,
        heapUsed: 39208080,
        external: 19488368 } },
  os: 
   { loadavg: [ 0.2236328125, 0.375, 0.30908203125 ],
     uptime: 298089 },
  trace: 
   [ { column: 83,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: null,
       line: 521,
       method: null,
       native: false },
     { column: 16,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 473,
       method: null,
       native: false },
     { column: 29,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: 'next',
       line: 5315,
       method: null,
       native: false },
     { column: 16,
       file: '/workspace/Assignment/server/node_modules/async/dist/async.js',
       function: null,
       line: 958,
       method: null,
       native: false },
     { column: 7,
       file: '/workspace/Assignment/server/controllers/fileManager.js',
       function: 'Timeout._onTimeout',
       line: 504,
       method: '_onTimeout',
       native: false },
     { column: 14,
       file: 'timers.js',
       function: 'ontimeout',
       line: 386,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'tryOnTimeout',
       line: 250,
       method: null,
       native: false },
     { column: 5,
       file: 'timers.js',
       function: 'Timer.listOnTimeout',
       line: 214,
       method: 'listOnTimeout',
       native: false } ],
  stack: 
   [ 'TypeError: Cannot read property \'toString\' of null',
     '    at /workspace/Assignment/server/controllers/fileManager.js:521:83',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:473:16',
     '    at next (/workspace/Assignment/server/node_modules/async/dist/async.js:5315:29)',
     '    at /workspace/Assignment/server/node_modules/async/dist/async.js:958:16',
     '    at Timeout._onTimeout (/workspace/Assignment/server/controllers/fileManager.js:504:7)',
     '    at ontimeout (timers.js:386:14)',
     '    at tryOnTimeout (timers.js:250:5)',
     '    at Timer.listOnTimeout (timers.js:214:5)' ] }
